### ISSUE TITLE
Erro de Parse em CSOSN

### ISSUE THREAD

**Issue by rodsnjr** [fincatto/nfe#44]
Na hora de dar parse numa XML com CSOSN 500 retorna este erro ...

java.lang.IllegalArgumentException: Nao foi possivel parsear o xml: cvc-enumeration-valid: O valor '500' não tem um aspecto válido em relação à enumeração '[102, 103, 300, 400]'. Deve ser um valor da enumeração.
	at com.fincatto.nfe310.parsers.NotaParser.notaParaObjeto(NotaParser.java:35)
	at com.bigriver.erp.modules.sales.factory.NfeFactory.getNota(NfeFactory.java:126)
	at com.bigriver.erp.modules.sales.factory.NfeFactory.getLoteNfe(NfeFactory.java:102)
	at com.bigriver.erp.nfe.TestarLotes.testarLotes(TestarLotes.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by jefperito** [comment]
Precisa verificar se o XSD na biblioteca está atualizado, eu creio que sim, pois esse é um erro na validação do XML gerado com o XSD disponibilizado pelo Sefaz

**Comment by jefperito** [comment]
o XML que você ta passando está com ICMSSN102?

**Comment by rodsnjr** [comment]
Sim, ICMSSN102, com código 500, o 500 e 900 da ENUMERAÇÃO tão retornando esse erro... os demais estão ok!

**Comment by jefperito** [comment]
Entendi...

Olhando o XSD da nfe 3.10o ICMSSN102 conta que só pode contem CSOSN 100/200/300 ou 400:

```
<xs:element name="ICMSSN102">
	<xs:annotation>
		<xs:documentation>Tributação do ICMS pelo SIMPLES NACIONAL e CSOSN=102, 103, 300 ou 400 (v.2.0))</xs:documentation>
	</xs:annotation>
	<xs:complexType>
		<xs:sequence>
			<xs:element name="orig" type="Torig">
				<xs:annotation>
					<xs:documentation>
						origem da mercadoria: 
							0 - Nacional 
							1 - Estrangeira - Importação direta 
							2 - Estrangeira - Adquirida no mercado interno (v2.0)
				</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="CSOSN">
				<xs:annotation>
					<xs:documentation>
						102 - Tributada pelo Simples Nacional sem permissão de crédito. 
						103 – Isenção do ICMS  no Simples Nacional para faixa de receita bruta.
						300 – Imune.
						400 – Não tributda pelo Simples Nacional (v.2.0) (v.2.0)
					</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:whiteSpace value="preserve"/>
						<xs:enumeration value="102"/>
						<xs:enumeration value="103"/>
						<xs:enumeration value="300"/>
						<xs:enumeration value="400"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>
```

Pode ser bug do XSD disponibilizado pelo governo, mas dae não tenho conhecimento técnico para avaliar se esse valor pode conter em um ICMSSN102
