### ISSUE TITLE
Problemas ao enviar pelo Mac

### ISSUE THREAD

**Issue by andregui7** [fincatto/nfe#55]
Olá, estou fazendo testes num Eclipse instalado em um MacBookPro. Está disparando este erro:

```org.xml.sax.SAXParseException; systemId: jar:file:/Users/andregui7/Programação/confeitaria/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/confeitaria_web/WEB-INF/lib/nfe-1.0-SNAPSHOT.jar!/com/fincatto/nfe310/validadores/xsd/schemas/enviNFe_v3.10.xsd; lineNumber: 4; columnNumber: 45; src-resolve: Não é possível resolver o nome 'TEnviNFe' para um componente 'type definition'.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:437)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr(XSDHandler.java:4162)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaError(XSDHandler.java:4145)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getGlobalDecl(XSDHandler.java:1741)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDElementTraverser.traverseNamedElement(XSDElementTraverser.java:405)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDElementTraverser.traverseGlobal(XSDElementTraverser.java:242)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.traverseSchemas(XSDHandler.java:1433)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:630)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:616)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:574)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:540)
	at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema(XMLSchemaFactory.java:255)
	at javax.xml.validation.SchemaFactory.newSchema(SchemaFactory.java:638)
	at com.fincatto.nfe310.validadores.xsd.XMLValidador.validaXml(XMLValidador.java:18)
	at com.fincatto.nfe310.validadores.xsd.XMLValidador.validaLote(XMLValidador.java:24)
	at com.fincatto.nfe310.webservices.WSFacade.enviaLote(WSFacade.java:49)
	at com.confeitaria.NFeUtil.enviarLote(NFeUtil.java:529)
	at com.confeitaria.ComandosDoClienteServlet.processarRequest(ComandosDoClienteServlet.java:909)
	at com.confeitaria.ComandosDoClienteServlet.processarRequestComTratamento(ComandosDoClienteServlet.java:87)
	at com.confeitaria.ComandosDoClienteServlet.doGet(ComandosDoClienteServlet.java:65)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:618)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1085)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1556)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1513)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)```

Resumindo: Não é possível resolver o nome 'TEnviNFe' para um componente 'type definition'.

Tem alguma sugestão?

**Comment by jefperito** [comment]
Oi, eu uso mac para o desenvolvimento e não lembro de ter tido esse tipo de problema, talvez foi pelo fato de você ter gerado um jar a parte, precisa verificar se a geracao do jar levou esses arquivos... tente adiciona-lo de outra forma ao projeto.

**Comment by andregui7** [comment]
Qual arquivo será que está faltando?

**Comment by andregui7** [comment]
Estou tentando rodar em um servidor Tomcat no meu site e dispara esse erro:

org.apache.axis2.AxisFault: Connection has been shutdown: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Eu consigo invocar o método enviaLote() e não dá erro algum, mas ao chamar o método consultaLote(), pra pegar os dados do protocolo, ele dispara o erro. Preciso assinar o certificado no meu servidor web?

**Comment by fincatto** [comment]
Temos um forum para sanar duvidas e conseguir ajuda com a comunidade: http://www.edsonmoretti.com.br/nfe/

**Comment by andregui7** [comment]
Olá, não consigo me inscrever no fórum, não aparece a imagem de captcha. Aparece: To use reCAPTCHA you must get an API key from https://www.google.com/recaptcha/admin/create

**Comment by fincatto** [comment]
Falei agora com o rapaz que administra o Forum e ele resolveu prontamente. 
Podes testar novamente, por favor?
Obrigado.
